version: '3'
services:
  app:
    image: "indeanest-project"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://root:password@mongo:27017
      DB_NAME: indeanest
      JWT_SECRET: indeanest
    networks:
      - indeanest-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - indeanest-network
    
volumes:
  mongo_data:

networks:
  indeanest-network:
    driver: bridge


#version: '3'
# services:
#   app:
#     image: triple3a/gosurvey:v1
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#     environment:
#       SERVER_PORT: 8080
#       MONGO_URI: mongodb://db:27017

#   db:
#     image: mongo:latest
#     restart: always
#     ports:
#       - "27017:27017"