version: '3'
services:
  app:
    image: "indeanest-project"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://root:password@mongo:27017
      DB_NAME: indeanest
      JWT_SECRET: indeanest
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
    networks:
      - indeanest-network

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    networks:
      - indeanest-network
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - indeanest-network

volumes:
  mongo_data:
  redis_data:

networks:
  indeanest-network:
    driver: bridge
